import type { SpecialOfferProduct } from "../types";


export const SPECIAL_OFFER_PRODUCTS: SpecialOfferProduct[] = [
  {
    id: "spec-cisco-2960x",
    name: "سوئیچ ۲۴ پورت سیسکو مدل WS-C2960X-24PS-L",
    slug: "cisco-ws-c2960x-24ps-l",
    description: "سوئیچ مدیریتی لایه ۲ سازمانی سیسکو با ۲۴ پورت گیگابیت اترنت PoE+ و توان ۳۷۰ وات به همراه ۴ اسلات SFP آپلینک گیگابیت.",
    brand: "Cisco Systems",
    price: 18200000,
    originalPrice: 26000000,
    discountPercent: 30,
    stockTotal: 12,
    stockRemaining: 3,
    rating: 4.9,
    reviewCount: 47,
    category: "workspace",
    inStock: true,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
    ],
    badges: ["فروش ویژه", "گارانتی طلایی ۳ ساله"],
    specs: ["۲۴ پورت PoE+ گیگابیت", "توان خروجی ۳۷۰W", "۴ پورت آپلینک SFP", "پشتیبانی FlexStack-Plus"],
  },
  {
    id: "spec-mikrotik-ccr2004",
    name: "روتر ابری میکروتیک مدل CCR2004-16G-2S+",
    slug: "mikrotik-ccr2004-16g-2s-plus",
    description: "روتر پرسرعت هسته سازمانی با پردازنده ۴ هسته‌ای Annapurna Labs، شانزده پورت گیگابیت اترنت و ۲ پورت فیبر نوری SFP+ با سرعت ۱۰ گیگابیت.",
    brand: "MikroTik",
    price: 28900000,
    originalPrice: 38500000,
    discountPercent: 25,
    stockTotal: 10,
    stockRemaining: 2,
    rating: 4.8,
    reviewCount: 38,
    category: "workspace",
    inStock: true,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1520869562399-e772f042f422?w=800&auto=format&fit=crop&q=80",
    ],
    badges: ["تخفیف ویژه", "پردازنده ۶۴ بیتی"],
    specs: ["۱۶ پورت اترنت گیگابیت", "۲ پورت SFP+ با سرعت 10G", "حافظه رم ۴ گیگابایت", "سیستم‌عامل RouterOS v7"],
  },
  {
    id: "spec-ubiquiti-u6-pro",
    name: "اکسس پوینت سقفی یوبیکیوتی مدل UniFi U6 Pro",
    slug: "ubiquiti-unifi-u6-pro",
    description: "اکسس پوینت پرقدرت وای‌فای ۶ سازمانی با پهنای باند تجمیعی ۵.۳ گیگابیت بر ثانیه، تکنولوژی MIMO 4x4 و اتصال همزمان بیش از ۳۵۰ کاربر.",
    brand: "Ubiquiti",
    price: 8900000,
    originalPrice: 12500000,
    discountPercent: 28,
    stockTotal: 20,
    stockRemaining: 4,
    rating: 4.9,
    reviewCount: 64,
    category: "workspace",
    inStock: true,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800&auto=format&fit=crop&q=80",
    ],
    badges: ["وای‌فای ۶", "پرفروش‌ترین"],
    specs: ["نرخ انتقال ۵.۳Gbps", "آنتن ۴×۴ MU-MIMO", "پوشش‌دهی ۱۴۰ متر مربع", "تغذیه از پورت PoE"],
  },
  {
    id: "spec-cisco-sfp-10g",
    name: "ماژول فیبر نوری ۱۰ گیگابیت سیسکو SFP-10G-SR",
    slug: "cisco-sfp-10g-sr-transceiver",
    description: "ترنسیور فیبر نوری مالتی‌مود با طول موج ۸۵۰ نانومتر، برد ۳۰۰ متر بر بستر کابل OM3، اتصال LC دوطرفه و سازگار با انواع سوئیچ سیسکو.",
    brand: "Cisco Systems",
    price: 4800000,
    originalPrice: 7400000,
    discountPercent: 35,
    stockTotal: 25,
    stockRemaining: 5,
    rating: 4.7,
    reviewCount: 29,
    category: "accessories",
    inStock: true,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&auto=format&fit=crop&q=80",
    ],
    badges: ["۳۵٪ تخفیف", "تضمین اصالت اورجینال"],
    specs: ["سرعت انتقال ۱۰ گیگابیت", "طول موج ۸۵۰nm مالتی‌مود", "برد انتقال تا ۳۰۰ متر", "پشتیبانی از پروتکل DOM"],
  },
  {
    id: "spec-legrand-patch-panel",
    name: "پچ پنل ۲۴ پورت کات ۶ لگراند Cat6 UTP تمام مس",
    slug: "legrand-cat6-utp-24port-patch-panel",
    description: "پچ پنل استاندارد رکمونت ۱ یونیت با ۲۴ پورت کیستون مجزا بدون نیاز به ابزار پانچ (Toolless) همراه با نگهدارنده کابل فلزی در پشت پنل.",
    brand: "Legrand France",
    price: 3250000,
    originalPrice: 4500000,
    discountPercent: 27,
    stockTotal: 18,
    stockRemaining: 6,
    rating: 4.8,
    reviewCount: 52,
    category: "workspace",
    inStock: true,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80",
    ],
    badges: ["فرانسه اصلی", "تاییدیه تست فلوک"],
    specs: ["استاندارد ۱۹ اینچ ۱U", "کیستون‌های پیچی سریع", "کانکتورهای روکش طلا", "مدیریت کابل پشت پنل"],
  },
  {
    id: "spec-rack-server-27u",
    name: "رک سرور ۲۷ یونیت عمق ۱۰۰ پایا سیستم مجهز به فن",
    slug: "paya-system-27u-server-rack-depth-100",
    description: "رک سروری صنعتی مستحکم با درب شیشه سکوریت فریم‌دار مشبک، رنگ الکترواستاتیک ضدخش پودری، ۴ عدد فن توربو بلبرینگی و چرخ‌های ترمزدار.",
    brand: "Paya System",
    price: 11900000,
    originalPrice: 15800000,
    discountPercent: 24,
    stockTotal: 8,
    stockRemaining: 2,
    rating: 4.9,
    reviewCount: 19,
    category: "workspace",
    inStock: true,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=800&auto=format&fit=crop&q=80",
    ],
    badges: ["فروش ویژه رک", "تحویل سریع باربری"],
    specs: ["عمق ۱۰۰cm استاندارد سرور", "مجهز به ۴ فن بلبرینگی", "درب‌های بغل بازشو قفل‌دار", "ظرفیت تحمل وزن تا ۸۰۰kg"],
  },
];
